# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/flamecat/Desktop/SOC_MV _THCP"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/flamecat/Desktop/SOC_MV _THCP"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/flamecat/Desktop/SOC_MV _THCP/CMakeFiles" "/Users/flamecat/Desktop/SOC_MV _THCP//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/flamecat/Desktop/SOC_MV _THCP/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named soc

# Build rule for target.
soc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soc
.PHONY : soc

# fast build rule for target.
soc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/build
.PHONY : soc/fast

LFU.o: LFU.cpp.o
.PHONY : LFU.o

# target to build an object file
LFU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LFU.cpp.o
.PHONY : LFU.cpp.o

LFU.i: LFU.cpp.i
.PHONY : LFU.i

# target to preprocess a source file
LFU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LFU.cpp.i
.PHONY : LFU.cpp.i

LFU.s: LFU.cpp.s
.PHONY : LFU.s

# target to generate assembly for a file
LFU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LFU.cpp.s
.PHONY : LFU.cpp.s

LRU.o: LRU.cpp.o
.PHONY : LRU.o

# target to build an object file
LRU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LRU.cpp.o
.PHONY : LRU.cpp.o

LRU.i: LRU.cpp.i
.PHONY : LRU.i

# target to preprocess a source file
LRU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LRU.cpp.i
.PHONY : LRU.cpp.i

LRU.s: LRU.cpp.s
.PHONY : LRU.s

# target to generate assembly for a file
LRU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/LRU.cpp.s
.PHONY : LRU.cpp.s

MV.o: MV.cpp.o
.PHONY : MV.o

# target to build an object file
MV.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MV.cpp.o
.PHONY : MV.cpp.o

MV.i: MV.cpp.i
.PHONY : MV.i

# target to preprocess a source file
MV.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MV.cpp.i
.PHONY : MV.cpp.i

MV.s: MV.cpp.s
.PHONY : MV.s

# target to generate assembly for a file
MV.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MV.cpp.s
.PHONY : MV.cpp.s

MVMB.o: MVMB.cpp.o
.PHONY : MVMB.o

# target to build an object file
MVMB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MVMB.cpp.o
.PHONY : MVMB.cpp.o

MVMB.i: MVMB.cpp.i
.PHONY : MVMB.i

# target to preprocess a source file
MVMB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MVMB.cpp.i
.PHONY : MVMB.cpp.i

MVMB.s: MVMB.cpp.s
.PHONY : MVMB.s

# target to generate assembly for a file
MVMB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/MVMB.cpp.s
.PHONY : MVMB.cpp.s

SOC.o: SOC.cpp.o
.PHONY : SOC.o

# target to build an object file
SOC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/SOC.cpp.o
.PHONY : SOC.cpp.o

SOC.i: SOC.cpp.i
.PHONY : SOC.i

# target to preprocess a source file
SOC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/SOC.cpp.i
.PHONY : SOC.cpp.i

SOC.s: SOC.cpp.s
.PHONY : SOC.s

# target to generate assembly for a file
SOC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/SOC.cpp.s
.PHONY : SOC.cpp.s

cacheItem.o: cacheItem.cpp.o
.PHONY : cacheItem.o

# target to build an object file
cacheItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cacheItem.cpp.o
.PHONY : cacheItem.cpp.o

cacheItem.i: cacheItem.cpp.i
.PHONY : cacheItem.i

# target to preprocess a source file
cacheItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cacheItem.cpp.i
.PHONY : cacheItem.cpp.i

cacheItem.s: cacheItem.cpp.s
.PHONY : cacheItem.s

# target to generate assembly for a file
cacheItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cacheItem.cpp.s
.PHONY : cacheItem.cpp.s

cache_manager.o: cache_manager.cpp.o
.PHONY : cache_manager.o

# target to build an object file
cache_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cache_manager.cpp.o
.PHONY : cache_manager.cpp.o

cache_manager.i: cache_manager.cpp.i
.PHONY : cache_manager.i

# target to preprocess a source file
cache_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cache_manager.cpp.i
.PHONY : cache_manager.cpp.i

cache_manager.s: cache_manager.cpp.s
.PHONY : cache_manager.s

# target to generate assembly for a file
cache_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/cache_manager.cpp.s
.PHONY : cache_manager.cpp.s

database_operation.o: database_operation.cpp.o
.PHONY : database_operation.o

# target to build an object file
database_operation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/database_operation.cpp.o
.PHONY : database_operation.cpp.o

database_operation.i: database_operation.cpp.i
.PHONY : database_operation.i

# target to preprocess a source file
database_operation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/database_operation.cpp.i
.PHONY : database_operation.cpp.i

database_operation.s: database_operation.cpp.s
.PHONY : database_operation.s

# target to generate assembly for a file
database_operation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/database_operation.cpp.s
.PHONY : database_operation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/main.cpp.s
.PHONY : main.cpp.s

queryItem.o: queryItem.cpp.o
.PHONY : queryItem.o

# target to build an object file
queryItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/queryItem.cpp.o
.PHONY : queryItem.cpp.o

queryItem.i: queryItem.cpp.i
.PHONY : queryItem.i

# target to preprocess a source file
queryItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/queryItem.cpp.i
.PHONY : queryItem.cpp.i

queryItem.s: queryItem.cpp.s
.PHONY : queryItem.s

# target to generate assembly for a file
queryItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/queryItem.cpp.s
.PHONY : queryItem.cpp.s

sqliteOP.o: sqliteOP.cpp.o
.PHONY : sqliteOP.o

# target to build an object file
sqliteOP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/sqliteOP.cpp.o
.PHONY : sqliteOP.cpp.o

sqliteOP.i: sqliteOP.cpp.i
.PHONY : sqliteOP.i

# target to preprocess a source file
sqliteOP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/sqliteOP.cpp.i
.PHONY : sqliteOP.cpp.i

sqliteOP.s: sqliteOP.cpp.s
.PHONY : sqliteOP.s

# target to generate assembly for a file
sqliteOP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/sqliteOP.cpp.s
.PHONY : sqliteOP.cpp.s

support_fun.o: support_fun.cpp.o
.PHONY : support_fun.o

# target to build an object file
support_fun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/support_fun.cpp.o
.PHONY : support_fun.cpp.o

support_fun.i: support_fun.cpp.i
.PHONY : support_fun.i

# target to preprocess a source file
support_fun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/support_fun.cpp.i
.PHONY : support_fun.cpp.i

support_fun.s: support_fun.cpp.s
.PHONY : support_fun.s

# target to generate assembly for a file
support_fun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/support_fun.cpp.s
.PHONY : support_fun.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soc.dir/build.make CMakeFiles/soc.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... soc"
	@echo "... LFU.o"
	@echo "... LFU.i"
	@echo "... LFU.s"
	@echo "... LRU.o"
	@echo "... LRU.i"
	@echo "... LRU.s"
	@echo "... MV.o"
	@echo "... MV.i"
	@echo "... MV.s"
	@echo "... MVMB.o"
	@echo "... MVMB.i"
	@echo "... MVMB.s"
	@echo "... SOC.o"
	@echo "... SOC.i"
	@echo "... SOC.s"
	@echo "... cacheItem.o"
	@echo "... cacheItem.i"
	@echo "... cacheItem.s"
	@echo "... cache_manager.o"
	@echo "... cache_manager.i"
	@echo "... cache_manager.s"
	@echo "... database_operation.o"
	@echo "... database_operation.i"
	@echo "... database_operation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... queryItem.o"
	@echo "... queryItem.i"
	@echo "... queryItem.s"
	@echo "... sqliteOP.o"
	@echo "... sqliteOP.i"
	@echo "... sqliteOP.s"
	@echo "... support_fun.o"
	@echo "... support_fun.i"
	@echo "... support_fun.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

